name: Build

on:
  workflow_call:

env:
  BUILD_TYPE: Release

jobs:
  build-client:
    name: Build client
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libncurses6
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --target twiiiiiter-client --config ${{env.BUILD_TYPE}}
  build-server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libsqlite0-dev
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --target twiiiiiter-server --config ${{env.BUILD_TYPE}}
