name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Test
    uses: ./.github/workflows/build.yml
  test-server:
    name: Test server
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Run tests
      working-directory: info4-reseau-sockets/tests
      run: cargo test
