name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-server-build:
    name: Test server (build)
    uses: ./.github/workflows/build.yml
  test-server:
    name: Test server
    runs-on: ubuntu-latest
    needs: test-server-build
    steps:
    - uses: actions-rs/toolchain@v1
    - name: Run tests
      run: cargo test
